[project]
name = "chat_ia"
version = "0.1.0"
description = "ChatBot com IA"
authors = [
    {name = "William Rodrigues",email = "williamr723@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "streamlit (>=1.61.1,<2.0.0)",
    "google-genai (>=2.17.0,<3.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
